local LSM = LibStub('LibSharedMedia-3.0')
LSM:Register("sound", "Unhalted: |cff8080FFNuke|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Nuke.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFDrop|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Drop.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FF5|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\5.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFLoS|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\LoS.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFRescue|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Rescue.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFMove|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Move.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFDown|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Down.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFDropping|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Dropping.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFRanged|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Ranged.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFSkull|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Skull.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFSeed|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Seed.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFSummon Stone|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Summon Stone.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFIdiot|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Idiot.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFKick|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Kick.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFGo Down|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Go Down.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFFocus|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Focus.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFAfflicted|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Afflicted.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFBuff|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Buff.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFDebuff|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Debuff.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFSpawning|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Spawning.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFClear|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Clear.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFDispel|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Dispel.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFBait|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Bait.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFClose|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Close.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFTransition|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Transition.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFSwitch|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Switch.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFCharges|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Charges.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFDrops Pool|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Drops Pool.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFPotion|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Potion.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FF1|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\1.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFPotions|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Potions.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFDefensive|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Defensive.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFStop|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Stop.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FF4|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\4.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFIncoming|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Incoming.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFStack|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Stack.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFOrbs|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Orbs.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFSpread|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Spread.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFTraps|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Traps.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFLow Stacks|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Low Stacks.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFSpawn|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Spawn.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFHide|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Hide.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFDiamond|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Diamond.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFTaunt|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Taunt.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFPick Up|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Pick Up.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFUp|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Up.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFMiddle|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Middle.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFPlatform 2|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Platform 2.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFNext|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Next.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFMoon|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Moon.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFCome Up|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Come Up.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFFrontal|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Frontal.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFPlatform 1|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Platform 1.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFPay Attention|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Pay Attention.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFCross|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Cross.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFMailbox|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Mailbox.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFHigh Stacks|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\High Stacks.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFJump|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Jump.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFTurn|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Turn.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFCages|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Cages.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFBackup|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Backup.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFSquare|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Square.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFSoak Now|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Soak Now.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFDon't Release|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Don't Release.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFP2|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\P2.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFLeap of Faith|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Leap of Faith.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFWinds|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Winds.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFYour Turn|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Your Turn.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFIntermission|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Intermission.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFFront|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Front.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFMark|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Mark.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFRepair|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Repair.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFAoE|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\AoE.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFCharging|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Charging.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFKnock|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Knock.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFOrb Incoming|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Orb Incoming.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFTurn Left|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Turn Left.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFSoak|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Soak.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFFeet|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Feet.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFFar|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Far.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFSoaking|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Soaking.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFSoon|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Soon.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFStar|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Star.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFGroup Up|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Group Up.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFOut|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Out.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFLeft|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Left.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFRight|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Right.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFOrb|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Orb.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFIncorporeal|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Incorporeal.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFP4|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\P4.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFAdds|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Adds.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FF3|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\3.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFPlatform 3|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Platform 3.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFCC|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\CC.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FF2|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\2.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFLeap|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Leap.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFTargeted|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Targeted.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFMelee|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Melee.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFOn You|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\On You.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFTurn Around|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Turn Around.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFDodge|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Dodge.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFMarks|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Marks.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFCauldron|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Cauldron.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFTotem|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Totem.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFInterrupt|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Interrupt.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFSoak Soon|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Soak Soon.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFTrap|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Trap.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFWatch Feet|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Watch Feet.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFBack|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Back.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFEmpowered|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Empowered.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFFeast|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Feast.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFCircle|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Circle.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFPull|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Pull.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFCage|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Cage.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFCharge|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Charge.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFP1|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\P1.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFDance|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Dance.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFGroup|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Group.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFHealthstones|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Healthstones.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFLook|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Look.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFGo Up|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Go Up.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFPlatform 4|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Platform 4.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFStop Casting|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Stop Casting.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFGate|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Gate.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFIn|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\In.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFTurn Right|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Turn Right.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFPI|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\PI.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFP3|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\P3.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFRun|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Run.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFPull In|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Pull In.mp3]])
LSM:Register("sound", "Unhalted: |cff8080FFMove Out|r", [[Interface\Addons\SharedMedia_Unhalted\Sounds\Move Out.mp3]])